### ISSUE TITLE
Drone does not move in Flightmare simulator

### ISSUE THREAD

**Issue by InsightofSPb** [dmar-bonn/ipp-al-framework#2]
Hello! Thank you and your team for your project!
I have faced a problem with the following thing. When I start a simulation with `python3 main_ros.py --config_file config/config_flightmare.yaml` with Flightmare launched before in other terminal by authors' command `roslaunch flightros rotors_gazebo.launch` the drone moves to the initial pose with height mentioned in config. And that's it. It does not plan any trajectory.
Can you give an advise how to fix it? 

Btw, I tried to download your binary files by `curl -LO https://phenoroam.phenorob.de/geonetwork/srv/api/records/be36e0bc-bb15-4e7c-b341-5754670ff29c/attachments/RPG_Flightmare.zip` and it crushes every time in 2-3 seconds. 

With Potsdam and RIT18 everything works fine.

**Comment by dlrudco** [comment]
same here. I think the authors are not maintaining the repo anymore. since the provided link for the RPG_Flightmare.zip is now blocked, I have downloaded the original zip file from the flightmare github. However, this seems to not have the proper sensor topics since the code stucks at "data_rgb = rospy.wait_for_message("/rgb", Image, timeout=None)" and "rostopic echo /rgb" outputs "WARNING: no messages received and simulated time is active. Is /clock being published?" error. 

I assume the modification the authors made in the custom zip-file was crucial for running this repo.

**Comment by dlrudco** [comment]
It turns out we have to modify the camera settings in the original cpp files to publish ros topics of '/rgb','/segmentation' by ourselves. you can refer to the 'camera' example code. However, even though I've managed to run the code, the FOV of the camera is still unknown but this I think I can conduct some trial and error to find the sweet spot

**Comment by InsightofSPb** [comment]
Hello! Thanks for your advice!
